### ISSUE TITLE
Setup slogan selector

### ISSUE THREAD

**Issue by retani** [intergestalt/2038-app#6]
- [x] work out user interaction. see the slogan slider swipe action
- [x] touch first, mouse second
- [x] setup json files for data
- [x] implement global language state
- [x] set the slogan slider acronyms to the current language
- [x] style according to design

![image](https://user-images.githubusercontent.com/3465427/114352287-ff2edf80-9b6b-11eb-8280-51a33e659763.png)

[2038_app_language_switch_3004.pdf](https://github.com/intergestalt/2038-app/files/6294471/2038_app_language_switch_3004.pdf)

![image](https://user-images.githubusercontent.com/3465427/114352323-08b84780-9b6c-11eb-9de1-eff72b363334.png)
