### ISSUE TITLE
implement the design

### ISSUE THREAD

**Issue by retani** [intergestalt/2038-app#7]
about half of it is already done

some of the things that are missing
- [x]  ![image](https://user-images.githubusercontent.com/3465427/114353423-49649080-9b6d-11eb-96d9-a8115d113373.png)

- [x]  ![image](https://user-images.githubusercontent.com/3465427/114353165-fbe82380-9b6c-11eb-8507-50edf95a812f.png)
- [x] button color  ![image](https://user-images.githubusercontent.com/3465427/114353208-0a363f80-9b6d-11eb-8d57-90932b29424f.png)
- [x] icon 
![image](https://user-images.githubusercontent.com/3465427/114353236-13271100-9b6d-11eb-8746-a8e23c55d3fe.png)
- [x] fade (use css mask and gradient and background-blend-mode)
![image](https://user-images.githubusercontent.com/3465427/114353269-1b7f4c00-9b6d-11eb-89f0-f483ab5660d8.png)
- [x] distances 
![image](https://user-images.githubusercontent.com/3465427/114353454-53868f00-9b6d-11eb-880f-d44d9099e930.png)
- [x] responsive design for wide screen 
![image](https://user-images.githubusercontent.com/3465427/124358647-85b20500-dc21-11eb-92c1-0a752755c89f.png)

- [x] responsive design for tall screen ("A")
![image](https://user-images.githubusercontent.com/3465427/124358616-69ae6380-dc21-11eb-900c-8bc10066b1c7.png)

[2038_app_sketches_0904_designs.pdf](https://github.com/intergestalt/2038-app/files/6294498/2038_app_sketches_0904_designs.pdf)
[2038_app_sketches_0904_comments.pdf](https://github.com/intergestalt/2038-app/files/6294501/2038_app_sketches_0904_comments.pdf)
