### ISSUE TITLE
maybe replace text with image

### ISSUE THREAD

**Issue by retani** [intergestalt/2038-app#9]
the slogans are rendered text. this is cool, but has some downsides.

- there are encoding problems for chinese text on some devices
- the chinese font is huge (25MB or so)
- therefore, loading takes long, need a loading state
- sometimes the loading fails, and we don't know why and when
- first priority is to make it work with text, as it is, and to evaluate what the problems are. 

alternative: use transparent image to display text. 

this requires:

- [ ] change zdog to use image
- [ ] change slogan-language-screen to use images
- [ ] make designers do all the images
- [ ] load the images
- ...

**Comment by bootsa** [comment]
Browser stack shows similar...
![image](https://user-images.githubusercontent.com/22413/122758363-00ca0180-d299-11eb-95f9-53d15cd31d89.png)
iPhone 12 Mini, iOS 14, Safari

Although it happens right from the start and affects latin based slogans too:
![image](https://user-images.githubusercontent.com/22413/122758682-61593e80-d299-11eb-8553-0912957ac3ff.png)

![image](https://user-images.githubusercontent.com/22413/122758740-70d88780-d299-11eb-8dd8-e09c2ac1f964.png)

Also appears to happen without granting camera and sensor access (see background).

**Comment by bootsa** [comment]
Same thing on iOS 14 Chrome... though weirdly can't click the authorisation button:
![image](https://user-images.githubusercontent.com/22413/122766091-6c17d180-d2a1-11eb-894e-8911097aa30d.png)

**Comment by retani** [comment]
Okay, that's good for testing. And it happens even without sensor access?!
Can you find out more about it - maybe reducing the font helps

**Comment by bootsa** [comment]
Yeah, happens even without sensor access.

Seems to happen on all iPhones running iOS 12, 13 and 14. Sometimes on 12 and 13 it renders without problems except on refresh and then seems to effect all languages.

iOS 11 loads the rest of the app but not the slogan and then the rest of the app disappears when changing slogan (possibly also to do with the size of the font).

iOS 10 and 9 don't stretch the authorise screen and also have the rest of the app disappear when changing slogan or authoirising sensor and camera access:
![image](https://user-images.githubusercontent.com/22413/122771486-c4050700-d2a6-11eb-89a6-c973af768b46.png)

iOS 8 and 7 (and below?) complain about not being able to establish a secure connection and don't load the app at all:
![image](https://user-images.githubusercontent.com/22413/122771655-ed259780-d2a6-11eb-806c-197fb5573824.png)

OK, will make a subset font and see how that works.

**Comment by bootsa** [comment]
:partying_face: Subsetting the font (currently 43.7 kB instead of 23 MB) seems to resolves the distorted text issue - at least when testing through Browserstack.

Would be good to see if it resolves the iPhone heating issue on a physical device.

### Font subsetting

requisites:
- [pyftsubset](https://fonttools.readthedocs.io/en/latest/subset/)
- woff to ttf converter ([online](https://cloudconvert.com/woff-to-ttf))

steps:
- run pyftsubset using full font (ARIALUNI.TTF) and pass in character string or text file for source characters (simply pass in config.json - a few bytes could be saved by parsing just the slogan text and akronyms but meh...) - from public/fonts folder:
```pyftsubset ARIALUNI.TTF --output-file="arial-2038.woff" --flavor="woff" --text-file=../../src/config.json```
- convert to ttf - tried otf which is also supported by zFont / Typr.js and might be slightly more performant / smaller but get an error about missing glyfs table.
- place subset font in fonts folder and alter zFont src in component.
- load up, try and break it through refresh - can't - do happy dance!

Sources:
- https://markoskon.com/creating-font-subsets/

**Comment by retani** [comment]
Only the glyphs that are used in config.json --> https://wakamaifondue.com/
